version: "3"

services:
  # Web Server Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
      - db

  #Database Service
  db:
    image: mysql
    container_name: mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: blog
      MYSQL_ROOT_PASSWORD: password

  # Redis
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
  # db:
  #   image: postgres
  #   container_name: postgres
  #   volumes:
  #     - ./postgresql/data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_DB: blog
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: password

  # Application Service
  app:
    container_name: blog
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
    working_dir: /var/www

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "3400:80"
    depends_on:
      - db
  # pgadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: pgAdmin
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - db
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: hanieasemi76@gmail.com
  #     PGADMIN_DEFAULT_PASSWORD: password

  s3:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    entrypoint: bash
    command: -c "/opt/bin/minio server /export --address :9999 --console-address :9001"
    volumes:
      - ./s3/data:/export
    ports:
      - 9000:9999
      - 9001:9001

  createbuckets:
    image: minio/mc
    depends_on:
      - s3
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add myminio http://s3:9999 minioadmin minioadmin) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb myminio/blog.private;
      /usr/bin/mc policy set public myminio/blog.private;
      exit 0;
      "
